[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_DRAWER_ENABLED = "false"
  NETLIFY_FEEDBACK_DISABLED = "true"
  DISABLE_NETLIFY_BADGE = "true"

[context.production.environment]
  NETLIFY_DRAWER_ENABLED = "false"
  NETLIFY_FEEDBACK_DISABLED = "true"
  DISABLE_NETLIFY_BADGE = "true"

[context.deploy-preview.environment]
  NETLIFY_DRAWER_ENABLED = "false"
  NETLIFY_FEEDBACK_DISABLED = "true"
  DISABLE_NETLIFY_BADGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
